# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.api.watch_api import WatchApi  # noqa: E501
from etcd_client.rest import ApiException


class TestWatchApi(unittest.TestCase):
    """WatchApi unit test stubs"""

    def setUp(self):
        self.api = etcd_client.api.watch_api.WatchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_watch_watch(self):
        """Test case for watch_watch

        Watch watches for events happening or that have happened. Both input and output are streams; the input stream is for creating and canceling watchers and the output stream sends events. One watch RPC can watch on multiple key ranges, streaming events for several watches at once. The entire event history can be watched starting from the last compaction revision.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
