# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.api.cluster_api import ClusterApi  # noqa: E501
from etcd_client.rest import ApiException


class TestClusterApi(unittest.TestCase):
    """ClusterApi unit test stubs"""

    def setUp(self):
        self.api = etcd_client.api.cluster_api.ClusterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cluster_member_add(self):
        """Test case for cluster_member_add

        MemberAdd adds a member into the cluster.  # noqa: E501
        """
        pass

    def test_cluster_member_list(self):
        """Test case for cluster_member_list

        MemberList lists all the members in the cluster.  # noqa: E501
        """
        pass

    def test_cluster_member_promote(self):
        """Test case for cluster_member_promote

        MemberPromote promotes a member from raft learner (non-voting) to raft voting member.  # noqa: E501
        """
        pass

    def test_cluster_member_remove(self):
        """Test case for cluster_member_remove

        MemberRemove removes an existing member from the cluster.  # noqa: E501
        """
        pass

    def test_cluster_member_update(self):
        """Test case for cluster_member_update

        MemberUpdate updates the member configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
