# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.api.lease_api import LeaseApi  # noqa: E501
from etcd_client.rest import ApiException


class TestLeaseApi(unittest.TestCase):
    """LeaseApi unit test stubs"""

    def setUp(self):
        self.api = etcd_client.api.lease_api.LeaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lease_lease_grant(self):
        """Test case for lease_lease_grant

        LeaseGrant creates a lease which expires if the server does not receive a keepAlive within a given time to live period. All keys attached to the lease will be expired and deleted if the lease expires. Each expired key generates a delete event in the event history.  # noqa: E501
        """
        pass

    def test_lease_lease_keep_alive(self):
        """Test case for lease_lease_keep_alive

        LeaseKeepAlive keeps the lease alive by streaming keep alive requests from the client to the server and streaming keep alive responses from the server to the client.  # noqa: E501
        """
        pass

    def test_lease_lease_leases(self):
        """Test case for lease_lease_leases

        LeaseLeases lists all existing leases.  # noqa: E501
        """
        pass

    def test_lease_lease_leases2(self):
        """Test case for lease_lease_leases2

        LeaseLeases lists all existing leases.  # noqa: E501
        """
        pass

    def test_lease_lease_revoke(self):
        """Test case for lease_lease_revoke

        LeaseRevoke revokes a lease. All keys attached to the lease will expire and be deleted.  # noqa: E501
        """
        pass

    def test_lease_lease_revoke2(self):
        """Test case for lease_lease_revoke2

        LeaseRevoke revokes a lease. All keys attached to the lease will expire and be deleted.  # noqa: E501
        """
        pass

    def test_lease_lease_time_to_live(self):
        """Test case for lease_lease_time_to_live

        LeaseTimeToLive retrieves lease information.  # noqa: E501
        """
        pass

    def test_lease_lease_time_to_live2(self):
        """Test case for lease_lease_time_to_live2

        LeaseTimeToLive retrieves lease information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
