# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.models.etcdserverpb_auth_user_get_request import EtcdserverpbAuthUserGetRequest  # noqa: E501
from etcd_client.rest import ApiException


class TestEtcdserverpbAuthUserGetRequest(unittest.TestCase):
    """EtcdserverpbAuthUserGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEtcdserverpbAuthUserGetRequest(self):
        """Test EtcdserverpbAuthUserGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = etcd_client.models.etcdserverpb_auth_user_get_request.EtcdserverpbAuthUserGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
