# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.api.maintenance_api import MaintenanceApi  # noqa: E501
from etcd_client.rest import ApiException


class TestMaintenanceApi(unittest.TestCase):
    """MaintenanceApi unit test stubs"""

    def setUp(self):
        self.api = etcd_client.api.maintenance_api.MaintenanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_maintenance_alarm(self):
        """Test case for maintenance_alarm

        Alarm activates, deactivates, and queries alarms regarding cluster health.  # noqa: E501
        """
        pass

    def test_maintenance_defragment(self):
        """Test case for maintenance_defragment

        Defragment defragments a member's backend database to recover storage space.  # noqa: E501
        """
        pass

    def test_maintenance_downgrade(self):
        """Test case for maintenance_downgrade

        Downgrade requests downgrades, verifies feasibility or cancels downgrade on the cluster version. Supported since etcd 3.5.  # noqa: E501
        """
        pass

    def test_maintenance_hash_kv(self):
        """Test case for maintenance_hash_kv

        HashKV computes the hash of all MVCC keys up to a given revision. It only iterates \"key\" bucket in backend storage.  # noqa: E501
        """
        pass

    def test_maintenance_move_leader(self):
        """Test case for maintenance_move_leader

        MoveLeader requests current leader node to transfer its leadership to transferee.  # noqa: E501
        """
        pass

    def test_maintenance_snapshot(self):
        """Test case for maintenance_snapshot

        Snapshot sends a snapshot of the entire backend from a member over a stream to a client.  # noqa: E501
        """
        pass

    def test_maintenance_status(self):
        """Test case for maintenance_status

        Status gets the status of the member.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
