# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.api.kv_api import KVApi  # noqa: E501
from etcd_client.rest import ApiException


class TestKVApi(unittest.TestCase):
    """KVApi unit test stubs"""

    def setUp(self):
        self.api = etcd_client.api.kv_api.KVApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_k_v_compact(self):
        """Test case for k_v_compact

        Compact compacts the event history in the etcd key-value store. The key-value store should be periodically compacted or the event history will continue to grow indefinitely.  # noqa: E501
        """
        pass

    def test_k_v_delete_range(self):
        """Test case for k_v_delete_range

        DeleteRange deletes the given range from the key-value store. A delete request increments the revision of the key-value store and generates a delete event in the event history for every deleted key.  # noqa: E501
        """
        pass

    def test_k_v_put(self):
        """Test case for k_v_put

        Put puts the given key into the key-value store. A put request increments the revision of the key-value store and generates one event in the event history.  # noqa: E501
        """
        pass

    def test_k_v_range(self):
        """Test case for k_v_range

        Range gets the keys in the range from the key-value store.  # noqa: E501
        """
        pass

    def test_k_v_txn(self):
        """Test case for k_v_txn

        Txn processes multiple requests in a single transaction. A txn request increments the revision of the key-value store and generates events with the same revision for every completed request. It is not allowed to modify the same key several times within one txn.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
