# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import etcd_client
from etcd_client.models.etcdserverpb_txn_response import EtcdserverpbTxnResponse  # noqa: E501
from etcd_client.rest import ApiException


class TestEtcdserverpbTxnResponse(unittest.TestCase):
    """EtcdserverpbTxnResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEtcdserverpbTxnResponse(self):
        """Test EtcdserverpbTxnResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = etcd_client.models.etcdserverpb_txn_response.EtcdserverpbTxnResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
