# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbLeaseTimeToLiveRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'keys': 'bool'
    }

    attribute_map = {
        'id': 'ID',
        'keys': 'keys'
    }

    def __init__(self, id=None, keys=None, _configuration=None):  # noqa: E501
        """EtcdserverpbLeaseTimeToLiveRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._keys = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if keys is not None:
            self.keys = keys

    @property
    def id(self):
        """Gets the id of this EtcdserverpbLeaseTimeToLiveRequest.  # noqa: E501

        ID is the lease ID for the lease.  # noqa: E501

        :return: The id of this EtcdserverpbLeaseTimeToLiveRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EtcdserverpbLeaseTimeToLiveRequest.

        ID is the lease ID for the lease.  # noqa: E501

        :param id: The id of this EtcdserverpbLeaseTimeToLiveRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def keys(self):
        """Gets the keys of this EtcdserverpbLeaseTimeToLiveRequest.  # noqa: E501

        keys is true to query all the keys attached to this lease.  # noqa: E501

        :return: The keys of this EtcdserverpbLeaseTimeToLiveRequest.  # noqa: E501
        :rtype: bool
        """
        return self._keys

    @keys.setter
    def keys(self, keys):
        """Sets the keys of this EtcdserverpbLeaseTimeToLiveRequest.

        keys is true to query all the keys attached to this lease.  # noqa: E501

        :param keys: The keys of this EtcdserverpbLeaseTimeToLiveRequest.  # noqa: E501
        :type: bool
        """

        self._keys = keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbLeaseTimeToLiveRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbLeaseTimeToLiveRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbLeaseTimeToLiveRequest):
            return True

        return self.to_dict() != other.to_dict()
