# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbMemberUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'peer_ur_ls': 'list[str]'
    }

    attribute_map = {
        'id': 'ID',
        'peer_ur_ls': 'peerURLs'
    }

    def __init__(self, id=None, peer_ur_ls=None, _configuration=None):  # noqa: E501
        """EtcdserverpbMemberUpdateRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._peer_ur_ls = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if peer_ur_ls is not None:
            self.peer_ur_ls = peer_ur_ls

    @property
    def id(self):
        """Gets the id of this EtcdserverpbMemberUpdateRequest.  # noqa: E501

        ID is the member ID of the member to update.  # noqa: E501

        :return: The id of this EtcdserverpbMemberUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EtcdserverpbMemberUpdateRequest.

        ID is the member ID of the member to update.  # noqa: E501

        :param id: The id of this EtcdserverpbMemberUpdateRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def peer_ur_ls(self):
        """Gets the peer_ur_ls of this EtcdserverpbMemberUpdateRequest.  # noqa: E501

        peerURLs is the new list of URLs the member will use to communicate with the cluster.  # noqa: E501

        :return: The peer_ur_ls of this EtcdserverpbMemberUpdateRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._peer_ur_ls

    @peer_ur_ls.setter
    def peer_ur_ls(self, peer_ur_ls):
        """Sets the peer_ur_ls of this EtcdserverpbMemberUpdateRequest.

        peerURLs is the new list of URLs the member will use to communicate with the cluster.  # noqa: E501

        :param peer_ur_ls: The peer_ur_ls of this EtcdserverpbMemberUpdateRequest.  # noqa: E501
        :type: list[str]
        """

        self._peer_ur_ls = peer_ur_ls

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbMemberUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbMemberUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbMemberUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
