# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbWatchCancelRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'watch_id': 'str'
    }

    attribute_map = {
        'watch_id': 'watch_id'
    }

    def __init__(self, watch_id=None, _configuration=None):  # noqa: E501
        """EtcdserverpbWatchCancelRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._watch_id = None
        self.discriminator = None

        if watch_id is not None:
            self.watch_id = watch_id

    @property
    def watch_id(self):
        """Gets the watch_id of this EtcdserverpbWatchCancelRequest.  # noqa: E501

        watch_id is the watcher id to cancel so that no more events are transmitted.  # noqa: E501

        :return: The watch_id of this EtcdserverpbWatchCancelRequest.  # noqa: E501
        :rtype: str
        """
        return self._watch_id

    @watch_id.setter
    def watch_id(self, watch_id):
        """Sets the watch_id of this EtcdserverpbWatchCancelRequest.

        watch_id is the watcher id to cancel so that no more events are transmitted.  # noqa: E501

        :param watch_id: The watch_id of this EtcdserverpbWatchCancelRequest.  # noqa: E501
        :type: str
        """

        self._watch_id = watch_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbWatchCancelRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbWatchCancelRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbWatchCancelRequest):
            return True

        return self.to_dict() != other.to_dict()
