# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbRequestOp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_delete_range': 'EtcdserverpbDeleteRangeRequest',
        'request_put': 'EtcdserverpbPutRequest',
        'request_range': 'EtcdserverpbRangeRequest',
        'request_txn': 'EtcdserverpbTxnRequest'
    }

    attribute_map = {
        'request_delete_range': 'request_delete_range',
        'request_put': 'request_put',
        'request_range': 'request_range',
        'request_txn': 'request_txn'
    }

    def __init__(self, request_delete_range=None, request_put=None, request_range=None, request_txn=None, _configuration=None):  # noqa: E501
        """EtcdserverpbRequestOp - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._request_delete_range = None
        self._request_put = None
        self._request_range = None
        self._request_txn = None
        self.discriminator = None

        if request_delete_range is not None:
            self.request_delete_range = request_delete_range
        if request_put is not None:
            self.request_put = request_put
        if request_range is not None:
            self.request_range = request_range
        if request_txn is not None:
            self.request_txn = request_txn

    @property
    def request_delete_range(self):
        """Gets the request_delete_range of this EtcdserverpbRequestOp.  # noqa: E501


        :return: The request_delete_range of this EtcdserverpbRequestOp.  # noqa: E501
        :rtype: EtcdserverpbDeleteRangeRequest
        """
        return self._request_delete_range

    @request_delete_range.setter
    def request_delete_range(self, request_delete_range):
        """Sets the request_delete_range of this EtcdserverpbRequestOp.


        :param request_delete_range: The request_delete_range of this EtcdserverpbRequestOp.  # noqa: E501
        :type: EtcdserverpbDeleteRangeRequest
        """

        self._request_delete_range = request_delete_range

    @property
    def request_put(self):
        """Gets the request_put of this EtcdserverpbRequestOp.  # noqa: E501


        :return: The request_put of this EtcdserverpbRequestOp.  # noqa: E501
        :rtype: EtcdserverpbPutRequest
        """
        return self._request_put

    @request_put.setter
    def request_put(self, request_put):
        """Sets the request_put of this EtcdserverpbRequestOp.


        :param request_put: The request_put of this EtcdserverpbRequestOp.  # noqa: E501
        :type: EtcdserverpbPutRequest
        """

        self._request_put = request_put

    @property
    def request_range(self):
        """Gets the request_range of this EtcdserverpbRequestOp.  # noqa: E501


        :return: The request_range of this EtcdserverpbRequestOp.  # noqa: E501
        :rtype: EtcdserverpbRangeRequest
        """
        return self._request_range

    @request_range.setter
    def request_range(self, request_range):
        """Sets the request_range of this EtcdserverpbRequestOp.


        :param request_range: The request_range of this EtcdserverpbRequestOp.  # noqa: E501
        :type: EtcdserverpbRangeRequest
        """

        self._request_range = request_range

    @property
    def request_txn(self):
        """Gets the request_txn of this EtcdserverpbRequestOp.  # noqa: E501


        :return: The request_txn of this EtcdserverpbRequestOp.  # noqa: E501
        :rtype: EtcdserverpbTxnRequest
        """
        return self._request_txn

    @request_txn.setter
    def request_txn(self, request_txn):
        """Sets the request_txn of this EtcdserverpbRequestOp.


        :param request_txn: The request_txn of this EtcdserverpbRequestOp.  # noqa: E501
        :type: EtcdserverpbTxnRequest
        """

        self._request_txn = request_txn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbRequestOp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbRequestOp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbRequestOp):
            return True

        return self.to_dict() != other.to_dict()
