# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbResponseHeader(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cluster_id': 'str',
        'member_id': 'str',
        'raft_term': 'str',
        'revision': 'str'
    }

    attribute_map = {
        'cluster_id': 'cluster_id',
        'member_id': 'member_id',
        'raft_term': 'raft_term',
        'revision': 'revision'
    }

    def __init__(self, cluster_id=None, member_id=None, raft_term=None, revision=None, _configuration=None):  # noqa: E501
        """EtcdserverpbResponseHeader - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cluster_id = None
        self._member_id = None
        self._raft_term = None
        self._revision = None
        self.discriminator = None

        if cluster_id is not None:
            self.cluster_id = cluster_id
        if member_id is not None:
            self.member_id = member_id
        if raft_term is not None:
            self.raft_term = raft_term
        if revision is not None:
            self.revision = revision

    @property
    def cluster_id(self):
        """Gets the cluster_id of this EtcdserverpbResponseHeader.  # noqa: E501

        cluster_id is the ID of the cluster which sent the response.  # noqa: E501

        :return: The cluster_id of this EtcdserverpbResponseHeader.  # noqa: E501
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this EtcdserverpbResponseHeader.

        cluster_id is the ID of the cluster which sent the response.  # noqa: E501

        :param cluster_id: The cluster_id of this EtcdserverpbResponseHeader.  # noqa: E501
        :type: str
        """

        self._cluster_id = cluster_id

    @property
    def member_id(self):
        """Gets the member_id of this EtcdserverpbResponseHeader.  # noqa: E501

        member_id is the ID of the member which sent the response.  # noqa: E501

        :return: The member_id of this EtcdserverpbResponseHeader.  # noqa: E501
        :rtype: str
        """
        return self._member_id

    @member_id.setter
    def member_id(self, member_id):
        """Sets the member_id of this EtcdserverpbResponseHeader.

        member_id is the ID of the member which sent the response.  # noqa: E501

        :param member_id: The member_id of this EtcdserverpbResponseHeader.  # noqa: E501
        :type: str
        """

        self._member_id = member_id

    @property
    def raft_term(self):
        """Gets the raft_term of this EtcdserverpbResponseHeader.  # noqa: E501

        raft_term is the raft term when the request was applied.  # noqa: E501

        :return: The raft_term of this EtcdserverpbResponseHeader.  # noqa: E501
        :rtype: str
        """
        return self._raft_term

    @raft_term.setter
    def raft_term(self, raft_term):
        """Sets the raft_term of this EtcdserverpbResponseHeader.

        raft_term is the raft term when the request was applied.  # noqa: E501

        :param raft_term: The raft_term of this EtcdserverpbResponseHeader.  # noqa: E501
        :type: str
        """

        self._raft_term = raft_term

    @property
    def revision(self):
        """Gets the revision of this EtcdserverpbResponseHeader.  # noqa: E501

        revision is the key-value store revision when the request was applied. For watch progress responses, the header.revision indicates progress. All future events recieved in this stream are guaranteed to have a higher revision number than the header.revision number.  # noqa: E501

        :return: The revision of this EtcdserverpbResponseHeader.  # noqa: E501
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this EtcdserverpbResponseHeader.

        revision is the key-value store revision when the request was applied. For watch progress responses, the header.revision indicates progress. All future events recieved in this stream are guaranteed to have a higher revision number than the header.revision number.  # noqa: E501

        :param revision: The revision of this EtcdserverpbResponseHeader.  # noqa: E501
        :type: str
        """

        self._revision = revision

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbResponseHeader, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbResponseHeader):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbResponseHeader):
            return True

        return self.to_dict() != other.to_dict()
