# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbWatchRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cancel_request': 'EtcdserverpbWatchCancelRequest',
        'create_request': 'EtcdserverpbWatchCreateRequest',
        'progress_request': 'EtcdserverpbWatchProgressRequest'
    }

    attribute_map = {
        'cancel_request': 'cancel_request',
        'create_request': 'create_request',
        'progress_request': 'progress_request'
    }

    def __init__(self, cancel_request=None, create_request=None, progress_request=None, _configuration=None):  # noqa: E501
        """EtcdserverpbWatchRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cancel_request = None
        self._create_request = None
        self._progress_request = None
        self.discriminator = None

        if cancel_request is not None:
            self.cancel_request = cancel_request
        if create_request is not None:
            self.create_request = create_request
        if progress_request is not None:
            self.progress_request = progress_request

    @property
    def cancel_request(self):
        """Gets the cancel_request of this EtcdserverpbWatchRequest.  # noqa: E501


        :return: The cancel_request of this EtcdserverpbWatchRequest.  # noqa: E501
        :rtype: EtcdserverpbWatchCancelRequest
        """
        return self._cancel_request

    @cancel_request.setter
    def cancel_request(self, cancel_request):
        """Sets the cancel_request of this EtcdserverpbWatchRequest.


        :param cancel_request: The cancel_request of this EtcdserverpbWatchRequest.  # noqa: E501
        :type: EtcdserverpbWatchCancelRequest
        """

        self._cancel_request = cancel_request

    @property
    def create_request(self):
        """Gets the create_request of this EtcdserverpbWatchRequest.  # noqa: E501


        :return: The create_request of this EtcdserverpbWatchRequest.  # noqa: E501
        :rtype: EtcdserverpbWatchCreateRequest
        """
        return self._create_request

    @create_request.setter
    def create_request(self, create_request):
        """Sets the create_request of this EtcdserverpbWatchRequest.


        :param create_request: The create_request of this EtcdserverpbWatchRequest.  # noqa: E501
        :type: EtcdserverpbWatchCreateRequest
        """

        self._create_request = create_request

    @property
    def progress_request(self):
        """Gets the progress_request of this EtcdserverpbWatchRequest.  # noqa: E501


        :return: The progress_request of this EtcdserverpbWatchRequest.  # noqa: E501
        :rtype: EtcdserverpbWatchProgressRequest
        """
        return self._progress_request

    @progress_request.setter
    def progress_request(self, progress_request):
        """Sets the progress_request of this EtcdserverpbWatchRequest.


        :param progress_request: The progress_request of this EtcdserverpbWatchRequest.  # noqa: E501
        :type: EtcdserverpbWatchProgressRequest
        """

        self._progress_request = progress_request

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbWatchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbWatchRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbWatchRequest):
            return True

        return self.to_dict() != other.to_dict()
