# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbLeaseTimeToLiveResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'ttl': 'str',
        'granted_ttl': 'str',
        'header': 'EtcdserverpbResponseHeader',
        'keys': 'list[str]'
    }

    attribute_map = {
        'id': 'ID',
        'ttl': 'TTL',
        'granted_ttl': 'grantedTTL',
        'header': 'header',
        'keys': 'keys'
    }

    def __init__(self, id=None, ttl=None, granted_ttl=None, header=None, keys=None, _configuration=None):  # noqa: E501
        """EtcdserverpbLeaseTimeToLiveResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._ttl = None
        self._granted_ttl = None
        self._header = None
        self._keys = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if ttl is not None:
            self.ttl = ttl
        if granted_ttl is not None:
            self.granted_ttl = granted_ttl
        if header is not None:
            self.header = header
        if keys is not None:
            self.keys = keys

    @property
    def id(self):
        """Gets the id of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501

        ID is the lease ID from the keep alive request.  # noqa: E501

        :return: The id of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EtcdserverpbLeaseTimeToLiveResponse.

        ID is the lease ID from the keep alive request.  # noqa: E501

        :param id: The id of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def ttl(self):
        """Gets the ttl of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501

        TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.  # noqa: E501

        :return: The ttl of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :rtype: str
        """
        return self._ttl

    @ttl.setter
    def ttl(self, ttl):
        """Sets the ttl of this EtcdserverpbLeaseTimeToLiveResponse.

        TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.  # noqa: E501

        :param ttl: The ttl of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :type: str
        """

        self._ttl = ttl

    @property
    def granted_ttl(self):
        """Gets the granted_ttl of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501

        GrantedTTL is the initial granted time in seconds upon lease creation/renewal.  # noqa: E501

        :return: The granted_ttl of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :rtype: str
        """
        return self._granted_ttl

    @granted_ttl.setter
    def granted_ttl(self, granted_ttl):
        """Sets the granted_ttl of this EtcdserverpbLeaseTimeToLiveResponse.

        GrantedTTL is the initial granted time in seconds upon lease creation/renewal.  # noqa: E501

        :param granted_ttl: The granted_ttl of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :type: str
        """

        self._granted_ttl = granted_ttl

    @property
    def header(self):
        """Gets the header of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501


        :return: The header of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :rtype: EtcdserverpbResponseHeader
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this EtcdserverpbLeaseTimeToLiveResponse.


        :param header: The header of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :type: EtcdserverpbResponseHeader
        """

        self._header = header

    @property
    def keys(self):
        """Gets the keys of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501

        Keys is the list of keys attached to this lease.  # noqa: E501

        :return: The keys of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._keys

    @keys.setter
    def keys(self, keys):
        """Sets the keys of this EtcdserverpbLeaseTimeToLiveResponse.

        Keys is the list of keys attached to this lease.  # noqa: E501

        :param keys: The keys of this EtcdserverpbLeaseTimeToLiveResponse.  # noqa: E501
        :type: list[str]
        """

        self._keys = keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbLeaseTimeToLiveResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbLeaseTimeToLiveResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbLeaseTimeToLiveResponse):
            return True

        return self.to_dict() != other.to_dict()
