# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbAuthUserAddRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hashed_password': 'str',
        'name': 'str',
        'options': 'AuthpbUserAddOptions',
        'password': 'str'
    }

    attribute_map = {
        'hashed_password': 'hashedPassword',
        'name': 'name',
        'options': 'options',
        'password': 'password'
    }

    def __init__(self, hashed_password=None, name=None, options=None, password=None, _configuration=None):  # noqa: E501
        """EtcdserverpbAuthUserAddRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hashed_password = None
        self._name = None
        self._options = None
        self._password = None
        self.discriminator = None

        if hashed_password is not None:
            self.hashed_password = hashed_password
        if name is not None:
            self.name = name
        if options is not None:
            self.options = options
        if password is not None:
            self.password = password

    @property
    def hashed_password(self):
        """Gets the hashed_password of this EtcdserverpbAuthUserAddRequest.  # noqa: E501


        :return: The hashed_password of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._hashed_password

    @hashed_password.setter
    def hashed_password(self, hashed_password):
        """Sets the hashed_password of this EtcdserverpbAuthUserAddRequest.


        :param hashed_password: The hashed_password of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :type: str
        """

        self._hashed_password = hashed_password

    @property
    def name(self):
        """Gets the name of this EtcdserverpbAuthUserAddRequest.  # noqa: E501


        :return: The name of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EtcdserverpbAuthUserAddRequest.


        :param name: The name of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def options(self):
        """Gets the options of this EtcdserverpbAuthUserAddRequest.  # noqa: E501


        :return: The options of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :rtype: AuthpbUserAddOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this EtcdserverpbAuthUserAddRequest.


        :param options: The options of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :type: AuthpbUserAddOptions
        """

        self._options = options

    @property
    def password(self):
        """Gets the password of this EtcdserverpbAuthUserAddRequest.  # noqa: E501


        :return: The password of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this EtcdserverpbAuthUserAddRequest.


        :param password: The password of this EtcdserverpbAuthUserAddRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbAuthUserAddRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbAuthUserAddRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbAuthUserAddRequest):
            return True

        return self.to_dict() != other.to_dict()
