# coding: utf-8

"""
    api/etcdserverpb/rpc.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from etcd_client.configuration import Configuration


class EtcdserverpbAuthRoleGetResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'header': 'EtcdserverpbResponseHeader',
        'perm': 'list[AuthpbPermission]'
    }

    attribute_map = {
        'header': 'header',
        'perm': 'perm'
    }

    def __init__(self, header=None, perm=None, _configuration=None):  # noqa: E501
        """EtcdserverpbAuthRoleGetResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._header = None
        self._perm = None
        self.discriminator = None

        if header is not None:
            self.header = header
        if perm is not None:
            self.perm = perm

    @property
    def header(self):
        """Gets the header of this EtcdserverpbAuthRoleGetResponse.  # noqa: E501


        :return: The header of this EtcdserverpbAuthRoleGetResponse.  # noqa: E501
        :rtype: EtcdserverpbResponseHeader
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this EtcdserverpbAuthRoleGetResponse.


        :param header: The header of this EtcdserverpbAuthRoleGetResponse.  # noqa: E501
        :type: EtcdserverpbResponseHeader
        """

        self._header = header

    @property
    def perm(self):
        """Gets the perm of this EtcdserverpbAuthRoleGetResponse.  # noqa: E501


        :return: The perm of this EtcdserverpbAuthRoleGetResponse.  # noqa: E501
        :rtype: list[AuthpbPermission]
        """
        return self._perm

    @perm.setter
    def perm(self, perm):
        """Sets the perm of this EtcdserverpbAuthRoleGetResponse.


        :param perm: The perm of this EtcdserverpbAuthRoleGetResponse.  # noqa: E501
        :type: list[AuthpbPermission]
        """

        self._perm = perm

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtcdserverpbAuthRoleGetResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtcdserverpbAuthRoleGetResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EtcdserverpbAuthRoleGetResponse):
            return True

        return self.to_dict() != other.to_dict()
